---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngx-srv-test01
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ngx-ingress-test01
  namespace: test01
spec:
  rules:
  - host: ngx-test01.brrnd.example.com #Exposed url 
    http:
      paths:
      - backend:
          serviceName: ngx-srv-test01
          servicePort: 80
        path: /
  tls:
  - hosts:
    - ngx-test01.brrnd.example.com #Exposed url
    secretName: nginx-ingress-tls #Certificate 
---
