
## VIP:



Execute below commsand to create VIP yaml file in manifests folder.
If you are using VIP then no need to create HA Proxy or Keep Alive.

VIP Image Version: 0.3.1

**Syntax:**

sudo docker run --network host --rm plndr/kube-vip:IMAGE_VERSION manifest pod --controlplane --interface ens192 --vip VIP_ADDRESS --arp --leaderElection | sudo tee /etc/kubernetes/manifests/vip.yaml


```

**Demo Output Of this command:** 
sudo docker run --network host --rm plndr/kube-vip:0.3.1 manifest pod --controlplane --interface ens192 --vip 192.168.0.220 --arp --leaderElection | sudo tee /etc/kubernetes/manifests/vip.yaml

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: kube-vip
  namespace: kube-system
spec:
  containers:
  - args:
    - manager
    env:
    - name: vip_arp
      value: "true"
    - name: vip_interface
      value: ens192
    - name: port
      value: "6443"
    - name: vip_cidr
      value: "32"
    - name: cp_enable
      value: "true"
    - name: cp_namespace
      value: kube-system
    - name: vip_leaderelection
      value: "true"
    - name: vip_leaseduration
      value: "5"
    - name: vip_renewdeadline
      value: "3"
    - name: vip_retryperiod
      value: "1"
    - name: vip_address
      value: 192.168.0.220
    image: plndr/kube-vip:0.3.1
    imagePullPolicy: Always
    name: kube-vip
    resources: {}
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_TIME
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
    name: kubeconfig
status: {}

```
